# Generated by Django 6.0.1 on 2026-01-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Kutubxona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='muallif',
            name='age',
            field=models.BigIntegerField(default=0),
            preserve_default=False,
        ),
    ]
