# Generated by Django 6.0 on 2026-01-02 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nashriyot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.BigIntegerField()),
                ('quantity', models.BigIntegerField()),
                ('kelgan_sana', models.DateField()),
                ('nashriyot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nashriyot.nashriyot')),
            ],
        ),
    ]
